task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 16G

docker_builder:
  timeout_in: 120m
  env:
    DOCKER_USERNAME: ENCRYPTED[76e0312f63d11131b00afd4321fec875d22e97ed1b277eacd8f87cbfe5b630dfc2f53c22b3abd700fc7227e4c5af7ec7]
    repo: ENCRYPTED[e8e9357fade043e2d48b19da123abd90518f73e95c7b1d568a156f5b4fab71265c1765ac8b1b96357d8ccf7e41c07aa7]
    DOCKER_PASSWORD: ENCRYPTED[6ba1ea44159f07fede4ba9596e72baaf15b3d1194ea5dc86fde8a80d2070a20359995000efa4336f6a86063163bd26c4]
  build_script: |
              docker build --tag $DOCKER_USERNAME/$repo:latest .

  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: |
           docker push $DOCKER_USERNAME/$repo:latest
