docker_builder:
  timeout_in: 120m
  cpu: 8
  memory: 15G
  env:
    DOCKER_USERNAME: ENCRYPTED[5f0d2e2398a0801d5e2ac3f5143c0ca930b798d57b5bcf6a9ea1eb19c32c1038cc93c0e8d0f99cd00dd55455714607a0]
    DOCKER_PASSWORD: ENCRYPTED[1bbfef07134e081dad58bc5525f86b014a4f0ce68eca16aec750422e68d23777081a24b25d5b708ef90e619b9e1462f6]
  build_script: docker build --tag $DOCKER_USERNAME/test:0.5-g .
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push $DOCKER_USERNAME/test:0.5-g
