task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 16G

docker_builder:
  timeout_in: 120m
  build_script: |
           docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
           docker buildx rm builder
           docker buildx create --name builder --driver docker-container --use
           docker buildx inspect --bootstrap
           docker buildx build --platform linux/arm64 .
