task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 16G

docker_builder:
  timeout_in: 120m
  build_script: |
           docker buildx create --name mybuilder --use --bootstrap
           docker buildx build --platform linux/arm64 .
