name: Ubuntu
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Creating User to Login
      run: |
       mkdir docker && cd docker
       wget https://raw.githubusercontent.com/ci-recovery-build/alp/da17706783bdde24d02565bfdaddd62157249df5/Dockerfile
       docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t alpine-qbit
       docker login -u ${{ secrets.user }} -p ${{ secrets.pass }}
       docker push ${{ secrets.user }}/alpine-qbit:latest
       
