name: Docker
on: 
  push:
    branches: [ arm64 ]
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Creating User to Login
      run: |
           docker buildx create --name builder --driver docker-container --use
           docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
           docker buildx rm builder
           docker buildx create --name builder --driver docker-container --use
           docker buildx inspect --bootstrap
           docker buildx build --platform linux/arm64 .
