name: Ubuntu
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Creating User to Login
      run: |
       docker login -u ${{ secrets.user }} -p ${{ secrets.pass }}
       git clone https://github.com/ci-recovery-build/alp.git
       cd alp
       docker build . --pull --file Dockerfile --tag alpine-qbit:1.0.0
       docker images
       sudo docker push ${{ secrets.user }}/alpine-qbit:1.0.0
       
