name: Ubuntu
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Creating User to Login
      run: |
       git clone https://github.com/ci-recovery-build/alp.git
       cd alp
       docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile --tag alpine-qbit/alpine-qbit:latest
       docker login -u ${{ secrets.user }} -p ${{ secrets.pass }}
       docker push alpine-qbit/alpine-qbit:latest
       
