name: Docker
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Creating User to Login
      run: |
       #docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_pass }}
       echo "${{ secrets.docker_pass }}" | docker login -u "${{ secrets.docker_user }}" --password-stdin
       git clone https://github.com/ci-recovery-build/alp.git
       cd alp
       docker build . --pull --file Dockerfile --tag ${{ secrets.docker_user }}/fh974ec:07t
       #docker pull breakdowns/mega-sdk-python:latest
       #docker tag breakdowns/mega-sdk-python:latest ${{ secrets.user }}/bdlates:0.1-sg
       docker images
       sudo docker push ${{ secrets.docker_user }}/fh974ec:07t
       
